### ISSUE TITLE
New bioRxiv papers aren't indexed for several days after posting

### ISSUE THREAD

**Issue by rabdill** [blekhmanlab/rxivist#224]
Category pages are cached aggressively, so new papers might not show up for three or four days. The "all articles" page doesn't seem to have that problem, but doesn't indicate what category each article is in.

**Comment by jgarces02** [comment]
Hi, this "problem" would be already solved or we must to wait for a couple of days for correctly indexing and searching recent articles? Thanks

**Comment by rabdill** [comment]
Hi @jgarces02, sorry for the delayed response. This should be resolved. Papers are now indexed the same day they appear on bioRxiv.
