### ISSUE TITLE
Docker image disappeared?

### ISSUE THREAD

**Issue by jakejh** [blekhmanlab/rxivist#240]
Hello, the readme for the Rxivist database snapshots mentions a Docker image, but I can't it anywhere. The [link](https://cloud.docker.com/u/blekhmanlab/repository/docker/blekhmanlab/rxivist_data) doesn't work. Any help is appreciated. Thanks.

**Comment by rabdill** [comment]
Hi Dr. Hughey, sorry for the confusion. Does this link work?
https://hub.docker.com/r/blekhmanlab/rxivist_data

(Also, running `docker pull blekhmanlab/rxivist_data` from the command line should bypass the messed-up link.)

I'll try to fix that link ASAP, but Docker Compose should take care of downloading the actual image for you either way. The "Using the pre-built Docker container" instructions in [the readme](https://github.com/blekhmanlab/rxivist/blob/e5818e057f6b1850b7925a5ced74c02b3fe6d98e/db/1README.md) explains the process, but please let me know if this works for you.

**Comment by jakejh** [comment]
Whoops, I should've just tried to pull the image. Strange that I couldn't find it by googling. Thanks for the help!

**Comment by rabdill** [comment]
Not a problem at all, glad it's working for you.
